In [1]:
# https://towardsdatascience.com/hands-on-generative-adversarial-networks-gan-for-signal-processing-with-python-ff5b8d78bd28

In [5]:
from numpy import hstack
from numpy import zeros
from numpy import ones
from numpy.random import rand
from numpy.random import randn
import numpy as np
import pandas as pd
from sklearn.utils import resample
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import LabelEncoder
from collections import Counter
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Input
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM
from matplotlib import pyplot
import matplotlib.pyplot as plt

In [6]:
%run ./read_file.ipynb

:: loading settings :: url = jar:file:/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml


Ivy Default Cache set to: /home/ec2-user/.ivy2/cache
The jars for the packages stored in: /home/ec2-user/.ivy2/jars
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-61210d25-8d89-4b49-a80d-a2e7b850f3c8;1.0
	confs: [default]
	found graphframes#graphframes;0.8.2-spark3.2-s_2.12 in spark-packages
	found org.slf4j#slf4j-api;1.7.16 in central
:: resolution report :: resolve 98ms :: artifacts dl 3ms
	:: modules in use:
	graphframes#graphframes;0.8.2-spark3.2-s_2.12 from spark-packages in [default]
	org.slf4j#slf4j-api;1.7.16 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
	------------------------------

23/04/15 22:36:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).


23/04/15 22:36:25 WARN SparkConf: Note that spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone/kubernetes and LOCAL_DIRS in YARN).


In [7]:
# https://stackoverflow.com/questions/68036975/valueerror-shape-must-be-at-least-rank-3-but-is-rank-2-for-node-biasadd
# config for rank error in lstm
tf.keras.backend.set_image_data_format("channels_last")

pd.set_option('display.max_columns', None)

In [10]:
ds = spark.read.parquet(*["s3a://sapient-bucket-trusted/prod/graph/encoded/real/23Sep3/*"]) \
                .withColumn("event_sequence",col('event_sequence').cast('string')) \
                .cache()

In [11]:
tot = ds.count()

In [12]:
ds.groupBy("mal_trace") \
    .count() \
    .withColumnRenamed('count', 'cnt_per_group') \
    .withColumn('perc_of_count_total', (col('cnt_per_group') / tot) * 100 ) \
    .sort("perc_of_count_total").show()

+---------+-------------+-------------------+
|mal_trace|cnt_per_group|perc_of_count_total|
+---------+-------------+-------------------+
|        1|       118763| 0.6835843967111419|
|        0|     17254805|  99.31641560328886|
+---------+-------------+-------------------+



In [13]:
# Set Config
max_length = 6
sequence_length = 6
max_features = 6
padding_type = 'post'
trunc_type = 'post'
num_samples = 10

In [32]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=max_features)

In [33]:
ds_events = ds.select('event_sequence').rdd.flatMap(lambda x: x).collect()

In [34]:
# get vocab for full dataset 
tokenizer.fit_on_texts(ds_events)

In [35]:
ds_lim = ds.limit(num_samples).cache()
ds_events = ds_lim.select('event_sequence').rdd.flatMap(lambda x: x).collect()

In [36]:
# get only malicious data
ds_mal = ds.filter( col('mal_trace') == 1).cache()
ds.unpersist()

DataFrame[Trace: bigint, mal_trace: int, malicious: int, event_sequence: string]

In [37]:
dm_events = ds_mal.select('event_sequence').rdd.flatMap(lambda x: x).collect()

In [38]:
dm_labels = ds_mal.select('mal_trace').rdd.flatMap(lambda x: x).collect()

In [39]:
# Get our training data word index
word_index = tokenizer.word_index
vocab_count = len(word_index)

In [40]:
vocab_count

111

In [23]:
# one hot encode the data
dm_sequences = tokenizer.texts_to_sequences(dm_events)
dm_padded = tf.keras.utils.pad_sequences(dm_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
seq_enc_tensor = tf.one_hot(dm_padded, vocab_count)

In [27]:
ds_lim.select('event_sequence').limit(1).collect()

[Row(event_sequence='[01000000000100000100010000100000000000001, 10000000000010000010100001000000000001000, 10000000000100001000100001000000000010000]')]

In [31]:
seq_enc_tensor[0]

<tf.Tensor: shape=(6, 111), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0

In [29]:
seq_enc_tensor.shape

TensorShape([118763, 6, 111])

In [21]:
seq_enc_tensor.shape
# shape - (input_len, sequence_length, vocab_size)
input_len = seq_enc_tensor.shape[0]
sequence_length = seq_enc_tensor.shape[1]

In [22]:
def define_generator():
    model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(sequence_length, vocab_count)),
    tf.keras.layers.LSTM(128, return_sequences=True),
    tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(vocab_count, activation='softmax')),
    ])

    # Compile the model
    model.compile(loss='categorical_crossentropy', optimizer='adam')

    return model

def define_discriminator():
    model = tf.keras.Sequential([
            tf.keras.layers.Input(shape=(sequence_length, vocab_count)),
            tf.keras.layers.LSTM(128, return_sequences=False),
            tf.keras.layers.Dense(2, activation='softmax'),
    ])

    # Compile the model
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

    return model

def define_gan(generator, discriminator):
    discriminator.trainable = False
    model = tf.keras.Sequential()
    model.add(generator)
    model.add(discriminator)
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')
    
    return model

def generate_latent_space():
    n = tf.random.uniform(shape=[input_len, sequence_length, vocab_count], minval=1, maxval=vocab_count, dtype=tf.int32)
    return n

def generate_fake_samples(generator):
    # generate points in latent space & pass through generator
    x = generator.predict(generate_latent_space(), verbose=0)
    # create class labels
    y = zeros((input_len,1))
    return x, y

def generate_real_samples():
    x = seq_enc_tensor
    # create class labels
    y = ones((input_len,1))
    return x, y

def train(g_model, d_model, gan_model, epochs=5, n_eval=20):
    d_acc_history = []
    d_loss_history = []
    g_acc_history = []
    g_loss_history = []

    d_metric = tf.keras.metrics.SparseCategoricalAccuracy()
    g_metric = tf.keras.metrics.CategoricalAccuracy()

    # manually enumerate epochs
    for i in range(epochs):
        # prepare real samples
        x_real, y_real = generate_fake_samples(g_model)
        # prepare fake examples using the generator
        x_fake, y_fake = generate_fake_samples(g_model)

        # update discriminator
        d_real_loss = d_model.train_on_batch(x_real, y_real)
        d_fake_loss = d_model.train_on_batch(x_fake, y_fake)
        d_loss = 0.5 * (d_real_loss + d_fake_loss)

        d_real_pred = d_model.predict_on_batch(x_real)
        d_fake_pred = d_model.predict_on_batch(x_fake)

        d_metric.update_state(tf.concat([y_real, y_fake], axis=0), tf.concat([d_real_pred, d_fake_pred], axis=0))
        d_acc = d_metric.result().numpy()

        # prepare points in latent space as input for the generator
        x_gan = generate_latent_space()
        y_gan = ones((input_len, 1))
        g_loss = gan_model.train_on_batch(x_gan, y_gan)

        # update the generator via the discriminator's error
        gan_pred = gan_model.predict_on_batch(x_gan)
        g_metric.update_state(tf.one_hot(tf.cast(y_gan, tf.int32), depth=2), gan_pred)
        g_acc = g_metric.result().numpy()

        d_acc_history.append(d_acc)
        d_loss_history.append(d_loss)
        g_acc_history.append(g_acc)
        g_loss_history.append(g_loss)

        if i % n_eval == 0:
            print(f"Epoch {i}: Discriminator Loss: {d_loss}, Discriminator Accuracy: {d_acc}, Generator Loss: {g_loss}, Generator Accuracy: {g_acc}")

    return d_acc_history, d_loss_history, g_acc_history, g_loss_history

In [23]:
generator = define_generator()
discriminator = define_discriminator()
gan = define_gan(generator, discriminator)

In [24]:
epochs = 101
d_acc_history, d_loss_history, g_acc_history, g_loss_history = train(generator, discriminator, gan, epochs=epochs)

4/4 [==============================] - 2s 2ms/step


InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_4_device_/job:localhost/replica:0/task:0/device:CPU:0}} TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.int32), but the yielded element was [[[0.00784405 0.01363464 0.00795084 ... 0.00616735 0.01232874 0.00930799]
  [0.00743604 0.01299697 0.00657471 ... 0.00857116 0.01247007 0.01078571]
  [0.00660481 0.00816573 0.00864302 ... 0.00780875 0.01493056 0.01225976]
  [0.01089922 0.00896515 0.0062316  ... 0.00620996 0.0120111  0.00710753]
  [0.00853574 0.0143795  0.0166215  ... 0.00633353 0.01574256 0.00595049]
  [0.01126612 0.01166151 0.00304855 ... 0.00881959 0.0092577  0.00451845]]

 [[0.00901932 0.01744283 0.0126614  ... 0.0051707  0.0067511  0.01264073]
  [0.00937799 0.01681233 0.00838365 ... 0.00519401 0.01234819 0.00877401]
  [0.01010063 0.01713853 0.00942147 ... 0.00670861 0.01917028 0.0098217 ]
  [0.00698665 0.01906229 0.00689812 ... 0.00844652 0.00837909 0.00722283]
  [0.00642558 0.00801662 0.00641306 ... 0.00865609 0.00958089 0.0129503 ]
  [0.012514   0.00982862 0.00653447 ... 0.01629108 0.00858043 0.01294903]]

 [[0.01168932 0.01072754 0.00446282 ... 0.01017345 0.01357007 0.0075546 ]
  [0.00711788 0.02343464 0.00823045 ... 0.00713765 0.01143885 0.00887725]
  [0.00726337 0.01336324 0.01039504 ... 0.00479237 0.01452046 0.01611213]
  [0.00844331 0.01957811 0.00758222 ... 0.00822655 0.01099372 0.00893688]
  [0.01294964 0.01274304 0.00759487 ... 0.01699475 0.01217456 0.00511607]
  [0.01069593 0.00999451 0.01246619 ... 0.01275391 0.00916322 0.01002251]]

 ...

 [[0.0071698  0.01665911 0.01019003 ... 0.00534528 0.01018087 0.00948511]
  [0.00602717 0.01360997 0.0104102  ... 0.00674121 0.00906293 0.01796024]
  [0.00478603 0.0110727  0.00610275 ... 0.00517731 0.01377118 0.01704021]
  [0.00670524 0.01187402 0.00813616 ... 0.01004024 0.01256021 0.01039293]
  [0.00617699 0.01069959 0.00663627 ... 0.00709241 0.01170715 0.0083324 ]
  [0.00680568 0.01763043 0.01094075 ... 0.01005474 0.01359353 0.0070264 ]]

 [[0.00560598 0.01862064 0.00643899 ... 0.01564105 0.00751078 0.01364231]
  [0.00730061 0.01720654 0.00569534 ... 0.00774755 0.01834954 0.01045312]
  [0.01243223 0.01369837 0.00852198 ... 0.00909312 0.01128154 0.0063348 ]
  [0.00629803 0.02141227 0.00831497 ... 0.00662649 0.02291891 0.0074902 ]
  [0.01139779 0.01380648 0.01799767 ... 0.00533533 0.01638228 0.00993858]
  [0.00746125 0.00976811 0.01449763 ... 0.00673519 0.01113056 0.00573259]]

 [[0.00866404 0.0106354  0.00790299 ... 0.00938455 0.00953305 0.00871722]
  [0.0067823  0.01704649 0.00853296 ... 0.00961295 0.00982589 0.01174172]
  [0.00463716 0.02216605 0.00772885 ... 0.00809792 0.00928158 0.0097446 ]
  [0.00792143 0.02060956 0.01374969 ... 0.00686169 0.01472474 0.00934699]
  [0.00460164 0.01596515 0.01950155 ... 0.0045944  0.01449619 0.0141474 ]
  [0.00820918 0.01899235 0.00893106 ... 0.00505789 0.01207003 0.01020742]]].
Traceback (most recent call last):

  File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1045, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/tensorflow/python/data/util/nest.py", line 377, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/tensorflow/python/data/util/nest.py", line 278, in assert_shallow_structure
    raise TypeError(

TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: 'ndarray'.


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/tensorflow/python/ops/script_ops.py", line 271, in __call__
    ret = func(*args)

  File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1047, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.int32), but the yielded element was [[[0.00784405 0.01363464 0.00795084 ... 0.00616735 0.01232874 0.00930799]
  [0.00743604 0.01299697 0.00657471 ... 0.00857116 0.01247007 0.01078571]
  [0.00660481 0.00816573 0.00864302 ... 0.00780875 0.01493056 0.01225976]
  [0.01089922 0.00896515 0.0062316  ... 0.00620996 0.0120111  0.00710753]
  [0.00853574 0.0143795  0.0166215  ... 0.00633353 0.01574256 0.00595049]
  [0.01126612 0.01166151 0.00304855 ... 0.00881959 0.0092577  0.00451845]]

 [[0.00901932 0.01744283 0.0126614  ... 0.0051707  0.0067511  0.01264073]
  [0.00937799 0.01681233 0.00838365 ... 0.00519401 0.01234819 0.00877401]
  [0.01010063 0.01713853 0.00942147 ... 0.00670861 0.01917028 0.0098217 ]
  [0.00698665 0.01906229 0.00689812 ... 0.00844652 0.00837909 0.00722283]
  [0.00642558 0.00801662 0.00641306 ... 0.00865609 0.00958089 0.0129503 ]
  [0.012514   0.00982862 0.00653447 ... 0.01629108 0.00858043 0.01294903]]

 [[0.01168932 0.01072754 0.00446282 ... 0.01017345 0.01357007 0.0075546 ]
  [0.00711788 0.02343464 0.00823045 ... 0.00713765 0.01143885 0.00887725]
  [0.00726337 0.01336324 0.01039504 ... 0.00479237 0.01452046 0.01611213]
  [0.00844331 0.01957811 0.00758222 ... 0.00822655 0.01099372 0.00893688]
  [0.01294964 0.01274304 0.00759487 ... 0.01699475 0.01217456 0.00511607]
  [0.01069593 0.00999451 0.01246619 ... 0.01275391 0.00916322 0.01002251]]

 ...

 [[0.0071698  0.01665911 0.01019003 ... 0.00534528 0.01018087 0.00948511]
  [0.00602717 0.01360997 0.0104102  ... 0.00674121 0.00906293 0.01796024]
  [0.00478603 0.0110727  0.00610275 ... 0.00517731 0.01377118 0.01704021]
  [0.00670524 0.01187402 0.00813616 ... 0.01004024 0.01256021 0.01039293]
  [0.00617699 0.01069959 0.00663627 ... 0.00709241 0.01170715 0.0083324 ]
  [0.00680568 0.01763043 0.01094075 ... 0.01005474 0.01359353 0.0070264 ]]

 [[0.00560598 0.01862064 0.00643899 ... 0.01564105 0.00751078 0.01364231]
  [0.00730061 0.01720654 0.00569534 ... 0.00774755 0.01834954 0.01045312]
  [0.01243223 0.01369837 0.00852198 ... 0.00909312 0.01128154 0.0063348 ]
  [0.00629803 0.02141227 0.00831497 ... 0.00662649 0.02291891 0.0074902 ]
  [0.01139779 0.01380648 0.01799767 ... 0.00533533 0.01638228 0.00993858]
  [0.00746125 0.00976811 0.01449763 ... 0.00673519 0.01113056 0.00573259]]

 [[0.00866404 0.0106354  0.00790299 ... 0.00938455 0.00953305 0.00871722]
  [0.0067823  0.01704649 0.00853296 ... 0.00961295 0.00982589 0.01174172]
  [0.00463716 0.02216605 0.00772885 ... 0.00809792 0.00928158 0.0097446 ]
  [0.00792143 0.02060956 0.01374969 ... 0.00686169 0.01472474 0.00934699]
  [0.00460164 0.01596515 0.01950155 ... 0.0045944  0.01449619 0.0141474 ]
  [0.00820918 0.01899235 0.00893106 ... 0.00505789 0.01207003 0.01020742]]].


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]

In [ ]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

ax1.plot(range(1, epochs + 1), d_loss_history, label='Discriminator Loss')
ax1.plot(range(1, epochs + 1), g_loss_history, label='Generator Loss')
ax1.set_xlabel('Epochs')
ax1.set_ylabel('Loss')
ax1.legend()

ax2.plot(range(1, epochs + 1), d_acc_history, label='Discriminator Accuracy')
ax2.set_xlabel('Epochs')
ax2.set_ylabel('Accuracy')
ax2.legend()

plt.show()